#ifndef COMPONENTHEADERS_H
#define COMPONENTHEADERS_H
	#include <ComponentArch/Components/CCamera.hpp>
	#include <ComponentArch/Components/CNavmeshAgent.hpp>
	#include <ComponentArch/Components/CHabilityController.hpp>
	#include <ComponentArch/Components/CPlayerController.hpp>
	#include <ComponentArch/Components/CRigidBody.hpp>
	#include <ComponentArch/Components/CVida.hpp>
	#include <ComponentArch/Components/CClock.hpp>
	#include <ComponentArch/Components/CFlock.hpp>
	#include <ComponentArch/Components/ComponentHeaders.hpp>
	#include <ComponentArch/Components/CAIEnem.hpp>
	#include <ComponentArch/Components/CGun.hpp>
	#include <ComponentArch/Components/CTransform.hpp>
	#include <ComponentArch/Components/CRenderable_3D.hpp>
	#include <ComponentArch/Components/CAgent.hpp>
	#include <ComponentArch/Components/CStaticModel.hpp>
	#include <ComponentArch/Components/CDynamicModel.hpp>
	#include <ComponentArch/Components/CSimpleStaticRigidBody.hpp>
#endif
